### ISSUE TITLE
If element is longer than viewport returns false.

### ISSUE THREAD

**Issue by dsovino** [customd/jquery-visible#37] opened 2015-12-07 02:34 UTC
As described, if element being checked is longer than the window browser, it returns false when top and bottom of element are not visible.

**Comment by jayharland** [comment] 2016-02-04 23:42
Got the same problem over here. If the top or bottom of the element isn't in the window, even if there is a ton of content from the element in the window, it returns false.

Any ideas?

**Comment by dubaaron** [comment] 2016-02-06 02:11
Isn't that what the first optional parameter is for?  If you pass it 'true', it will return true if any part of the given element is visible.  From the [readme](https://github.com/customd/jquery-visible/blob/master/README.markdown), and [website](https://www.customd.com/articles/13/checking-if-an-element-is-visible-on-screen-using-jquery):

> This basic check will return true if the entire element is visible to the user (within the visual viewport).
> 
> `$('#element').visible();`
>
> If you'd like to check for ANY PART of the element, you can use the following:
> 
> `$('#element').visible( true );`

**Comment by frafor1988** [comment] 2016-03-02 15:32
I've updated to 1.2.0 today and after a bit of testing, I can confirm the issue: when the top border of the div (may it be the div itself, or the padding) touches to top border of the viewport, then .visible() evaluates to false even if .visible(true) is specified!

**Comment by jayharland** [comment] 2016-03-02 15:52
@dubaaron 

Using the optional first parameter still acts as though the element isn't visible even when it is taking up the entire screen and just it's top and bottom edges aren't visible.

> If you'd like to check for ANY PART of the element, you can use the following:
> 
> $('#element').visible( true );

It does not see the middle as "ANY PART", it only checks the corners, so if they aren't visible it returns false. When the content is long enough that it needs scrolling, it does not work as desired.

Since time was a factor, I scrapped this plugin and used something different (https://github.com/moagrius/isOnScreen).

Thank you though to the developers of this plugin because it's still pretty nice.

**Comment by frafor1988** [comment] 2016-03-02 16:02
I've just tried the code posted on #16 but it doesn't solve the issue

@jayharland 
Thanks for suggesting isOnScreen, works just as expected :+1:

**Comment by smcmillen** [comment] 2016-12-12 19:32
This has been idle for a long while but in case anyone cares, you can resolve this issue with adding the following line of code...

`vVisible = (rec.top < 0 && rec.bottom > vpHeight) ? true : vVisible;`

right after line 35.  This statement just checks to see if the element top border is above the window top AND the bottom border is below the fold.

**Comment by mimani-s** [comment] 2016-12-20 09:53
@smcmillen Thanks, this works like charm, should be added in the repo itself.

**Comment by samatcd** [comment] 2017-03-18 10:48
Resolved in latest commit.

**Closed by samatcd** 2017-03-18 10:48 UTC
